modLoader="javafml" #mandatory
loaderVersion="[2,)" #mandatory
license="GNU LESSER GENERAL PUBLIC LICENSE"
logoBlur=false


[[mods]] #mandatory
modId="myrelax" #mandatory
version="1.0" #mandatory
displayName="Item Dictionary" #mandatory
authors="land" #optional
description="Item Dictionary"
displayURL=""

[[dependencies.myrelax]] #optional
modId="neoforge" #mandatory
type="required" #mandatory
versionRange="[20.5,)" #mandatory
ordering="NONE"
side="BOTH"

[[dependencies.myrelax]]
modId="minecraft"
type="required"
versionRange="[1.20.6,1.21)"
ordering="NONE"
side="BOTH"

